# Generated by Django 4.2.4 on 2023-12-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0002_alter_farmermodel_options_alter_farmermodel_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmermodel',
            name='username',
            field=models.CharField(default='default_username', max_length=30, unique=True),
        ),
    ]
