# Generated by Django 4.2.4 on 2023-12-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0003_alter_farmermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmermodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='farmermodel',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
