# Generated by Django 4.2.4 on 2023-12-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0005_alter_farmermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmermodel',
            name='username',
            field=models.CharField(default='default_username', max_length=30, unique=True),
        ),
    ]
