# Generated by Django 4.2.4 on 2023-12-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0007_remove_farmermodel_farmer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmermodel',
            options={},
        ),
        migrations.AlterModelManagers(
            name='farmermodel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='farmer_address',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='farmer_district',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='farmer_panchayat',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='farmermodel',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='farmermodel',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
